apiVersion: v1
kind: Pod
metadata:
  name: memory-oom-demo
  namespace: incident-platform
  labels:
    app.kubernetes.io/name: memory-oom-demo
    app.kubernetes.io/part-of: incident-platform
spec:
  restartPolicy: Never

  containers:
    - name: memory-consumer
      image: python:3.12-alpine
      imagePullPolicy: IfNotPresent

      command:
        - python
        - -c
        - |
          import time

          print("Tentative d'allocation de 100 MiB...")
          memory = bytearray(100 * 1024 * 1024)
          print("Allocation terminée.")
          time.sleep(300)

      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          cpu: 50m
          memory: 32Mi

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
