apiVersion: v1
kind: Pod
metadata:
  name: service-account-demo
  namespace: incident-platform
  labels:
    app.kubernetes.io/name: service-account-demo
    app.kubernetes.io/part-of: incident-platform
spec:
  serviceAccountName: incident-reader
  restartPolicy: Always

  containers:
    - name: demo
      image: busybox:1.36.1
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "3600"

      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          cpu: 50m
          memory: 32Mi

      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
