apiVersion: v1
kind: ConfigMap
metadata:
  name: incident-api-config
  namespace: incident-platform
  labels:
    app.kubernetes.io/name: incident-api
    app.kubernetes.io/part-of: incident-platform
    environment: local
data:
  APP_NAME: "incident-platform-api"
  APP_ENV: "local"
  LOG_LEVEL: "info"
