apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
  namespace: incident-platform
  labels:
    app.kubernetes.io/name: hello
    app.kubernetes.io/part-of: incident-platform
    environment: local
type: Opaque
stringData:
  DEMO_API_TOKEN: "fake-token-local-only"
  DEMO_DATABASE_PASSWORD: "fake-password-local-only"
