apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-local
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "88.3.0"

    helm:
      releaseName: monitoring
      values: |
        alertmanager:
          enabled: true

          config:
            global:
              resolve_timeout: 5m

            route:
              receiver: discord
              group_by:
                - alertname
                - service
              group_wait: 10s
              group_interval: 1m
              repeat_interval: 3h

            receivers:
              - name: 'null'

              - name: discord
                discord_configs:
                  - send_resolved: true
                    webhook_url_file: /etc/alertmanager/secrets/discord-webhook/url

          alertmanagerSpec:
            secrets:
              - discord-webhook

        grafana:
          enabled: true

          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: monitoring

        prometheus:
          prometheusSpec:
            retention: 6h
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}

        kubeEtcd:
          enabled: false

        kubeControllerManager:
          enabled: false

        kubeScheduler:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
