apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-local
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "88.3.0"

    helm:
      releaseName: monitoring
      values: |
        alertmanager:
          enabled: true

          config:
            global:
              resolve_timeout: 5m

            route:
              receiver: 'null'
              group_by:
                - alertname
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              routes:
                - receiver: 'null'
                  matchers:
                    - alertname = "Watchdog"

            receivers:
              - name: 'null'

          alertmanagerSpec:
            alertmanagerConfigSelector:
              matchLabels:
                alertconfig: incident-api-discord

            alertmanagerConfigMatcherStrategy:
              type: None

        grafana:
          enabled: true

          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: monitoring

        prometheus:
          prometheusSpec:
            retention: 6h
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}

        kubeEtcd:
          enabled: false

        kubeControllerManager:
          enabled: false

        kubeScheduler:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
