apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-local
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/labosnie/eks-gitops-config.git
    targetRevision: main
    path: applications/incident-api/local/postgresql

  destination:
    server: https://kubernetes.default.svc
    namespace: incident-platform

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
